# Generated by Django 4.1 on 2025-04-25 09:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('plan', '0001_resolve_dependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('participants', models.ManyToManyField(related_name='participants', to='crm.profile', verbose_name='Участники')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.direction')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название этапа')),
                ('position', models.IntegerField(default=1)),
                ('color', models.CharField(choices=[('Зелёный', 'Зелёный'), ('Жёлтый', 'Жёлтый'), ('Красный', 'Красный'), ('Серый', 'Серый')], default='Серый', max_length=256, verbose_name='Цвет')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='plan.project')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_agreed', models.BooleanField(default=False)),
                ('chat', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на командный чат')),
                ('drive', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Ссылка на гугл диск')),
                ('curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator', to='crm.profile')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.project')),
                ('students', models.ManyToManyField(blank=True, related_name='teams', to='crm.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('description', models.TextField(max_length=10000, verbose_name='Описание')),
                ('creation', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField(default=datetime.datetime(2025, 4, 25, 9, 39, 47, 740967), verbose_name='Дата создания')),
                ('end', models.DateTimeField(verbose_name='Время закрытия задачи')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_creators', to='crm.profile', verbose_name='Создатель задачи')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='plan.task', verbose_name='Родительская задача')),
                ('performers', models.ManyToManyField(related_name='performers', to='crm.profile', verbose_name='Исполнители')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.project', verbose_name='Проект')),
                ('responsible_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile', verbose_name='Ответственный')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.stage', verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_final', models.BooleanField(default=False, verbose_name='Конечный результат')),
                ('name', models.CharField(max_length=100, verbose_name='Название ссылки')),
                ('link', models.CharField(max_length=10000, verbose_name='Ссылка')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.team')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingRespond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('attending', models.BooleanField(default=False, verbose_name='Приду/Не приду')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting', to='plan.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='crm.profile')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='plan.project'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_go', models.BooleanField(default=False, verbose_name='Приду')),
                ('content', models.TextField(max_length=10000, verbose_name='Текст')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plan.meeting')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='plan.task')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Описание пункта')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Выполнено')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plan.checklist')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.profile')),
            ],
        ),
        migrations.AddField(
            model_name='checklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='plan.task'),
        ),
    ]
