# Generated by Django 4.1 on 2025-04-29 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 29, 9, 43, 7, 704199), verbose_name='Дата создания'),
        ),
    ]
