# Generated by Django 4.1 on 2025-05-06 01:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_alter_task_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Задача завершена'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='color',
            field=models.CharField(choices=[('#D9D9D9', 'Серый'), ('#AE4B88', 'Розовый'), ('#4B56AE', 'Фиолетовый'), ('#6BAE4B', 'Салатовый'), ('#AE644B', 'Коричневый')], default='#D9D9D9', max_length=256, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
    ]
