# Generated by Django 4.1 on 2025-05-10 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_task_created_at_task_is_completed_alter_stage_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='subtask',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtask', to='plan.task'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
