# Generated by Django 4.1 on 2025-04-25 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100, verbose_name='Ответ')),
                ('count', models.IntegerField(verbose_name='Полученный балл')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('stage', models.CharField(choices=[('Редактирование', 'Редактирование'), ('Набор участников', 'Набор участников'), ('Формирование команд', 'Формирование команд'), ('Проведение мероприятия', 'Проведение мероприятия'), ('Мероприятие завершено', 'Мероприятие завершено')], default='Редактирование', max_length=50, verbose_name='Этап')),
                ('start', models.DateField(verbose_name='Дата начала')),
                ('end', models.DateField(verbose_name='Дата окончания')),
                ('end_app', models.DateField(verbose_name='Дата окончания приема заявок')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('course', models.IntegerField(blank=True, null=True, verbose_name='Курс')),
                ('university', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название университета')),
                ('vk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ссылка VK')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место работы')),
                ('password_reset_token', models.CharField(blank=True, max_length=65, null=True)),
                ('password_reset_token_created', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=1000, verbose_name='Вопрос')),
                ('count', models.IntegerField(verbose_name='Количество баллов за вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название робота')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('type_action', models.CharField(default='', max_length=100, verbose_name='Тип действия')),
                ('status', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('parameters_template', models.TextField(default='{}', help_text='JSON-схема параметров', verbose_name='Шаблон параметров')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('is_positive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название триггера')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('type_condition', models.CharField(default='', max_length=100, verbose_name='Тип условия')),
                ('status', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('parameters_template', models.TextField(default='{}', help_text='JSON-схема параметров', verbose_name='Шаблон параметров')),
            ],
        ),
        migrations.CreateModel(
            name='True_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_answer', models.CharField(max_length=100, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.question')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название теста')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('entry', models.IntegerField(verbose_name='Порог прохождения в %')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.event')),
            ],
        ),
        migrations.CreateModel(
            name='Status_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Позиция')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.event')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.status')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('admin', 'Администратор'), ('organizer', 'Организатор'), ('direction_leader', 'Руководитель направления'), ('curator', 'Куратор'), ('projectant', 'Проектант')], default='projectant', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.test'),
        ),
        migrations.CreateModel(
            name='OrgChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ВК', 'ВК'), ('ТГ', 'ТГ')], max_length=100, verbose_name='Тип чата')),
                ('name', models.CharField(max_length=100, verbose_name='Название чата')),
                ('description', models.CharField(max_length=100, verbose_name='Описание чата')),
                ('link', models.CharField(max_length=100, verbose_name='Ссылка на чат')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.event')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция в очереди')),
                ('type_function', models.CharField(choices=[('robot', 'Робот'), ('trigger', 'Триггер')], max_length=10, verbose_name='Тип действия')),
                ('config', models.JSONField(verbose_name='Конфигурация параметров')),
                ('robot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.robot')),
                ('status_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='functions', to='crm.status_order')),
                ('trigger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.trigger')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='specializations',
            field=models.ManyToManyField(related_name='specializations', to='crm.specialization', verbose_name='Специализации'),
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название направления')),
                ('description', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Описание')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='crm.event')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions', to='crm.profile', verbose_name='Руководитель направления')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ВК', 'ВК'), ('ТГ', 'ТГ'), ('Почта', 'Почта'), ('Телефон', 'Телефон')], max_length=100, verbose_name='Тип контакта')),
                ('data', models.CharField(max_length=100, verbose_name='Реквезит')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Статус верификации')),
                ('verified_token', models.CharField(blank=True, max_length=100, null=True, verbose_name='Токен верификации')),
                ('token_created_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Ваш текст')),
                ('is_link', models.BooleanField(default=False, verbose_name='Состоит в чате?')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Заявка одобрена?')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Отзыв')),
                ('date_sub', models.DateTimeField(auto_now=True, verbose_name='Дата подачи')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.direction')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='crm.event')),
            ],
        ),
    ]
