# Generated by Django 4.1 on 2025-04-25 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('plan', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.project'),
        ),
        migrations.AddField(
            model_name='application',
            name='specialization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.specialization'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.status'),
        ),
        migrations.AddField(
            model_name='application',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.team'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.profile'),
        ),
        migrations.AddIndex(
            model_name='status_order',
            index=models.Index(fields=['event', 'number'], name='crm_status__event_i_1c45b1_idx'),
        ),
        migrations.AddIndex(
            model_name='status_order',
            index=models.Index(fields=['status', 'event'], name='crm_status__status__398fc6_idx'),
        ),
        migrations.AddConstraint(
            model_name='status_order',
            constraint=models.UniqueConstraint(fields=('event', 'number'), name='unique_event_position'),
        ),
        migrations.AddConstraint(
            model_name='status_order',
            constraint=models.UniqueConstraint(fields=('event', 'status'), name='unique_event_status'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('user', 'role_type', 'content_type', 'object_id')},
        ),
        migrations.AddConstraint(
            model_name='functionorder',
            constraint=models.UniqueConstraint(fields=('status_order', 'position'), name='unique_status_order_position'),
        ),
    ]
