# Generated by Django 4.1 on 2025-05-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата подачи'),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_sub',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
    ]
