# Generated by Django 4.1 on 2025-06-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_application_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stage',
            field=models.CharField(choices=[('Редактирование', 'Редактирование'), ('Набор участников', 'Набор участников'), ('Проведение мероприятия', 'Проведение мероприятия'), ('Мероприятие завершено', 'Мероприятие завершено')], default='Редактирование', max_length=50, verbose_name='Этап'),
        ),
    ]
